### PR TITLE
Add basic automated tests

### PR DESCRIPTION
**Pull request by jtorreggiani**
Firstly, I wanted to say the tau-prolog is awesome! It is a testament to amazing work from all of its contributors. I would love to contribute in anyway I can!

To help me better understand the implementation of the library I found it helpful to write units tests for code examples from the documentation. It occurred to me that it could be helpful to include them in the main repository to encourage code quality and prevent software regressions as features are added to the library.

In this PR I have included a suite of basic unit tests based on the Node.js code examples
from the tau-prolog manual http://tau-prolog.org/manual/compatibility-with-nodejs. I tried to follow the general JavaScript style I could infer from the library's source code. I installed [jest](https://github.com/facebook/jest) for running the tests via `npm` and added configure the `npm test` command to run the tests.

It is totally understandable if you do not want to add any external dependencies to the library even if only for testing purposes. Either way I hope this example of testing the code is useful. If it is not added in the main repository maybe it can be incorporated in some way for future development of the project.  

Excited to get your feedback!

### CODE REVIEW

**Comment by jariazavalverde** [comment]
Hi @jtorreggiani,

First of all, thank you very much for your contribution! We usually write unit tests with `jUnit`, although we still lack tests for many of the built-in predicates and libraries.

I don't know much about npm. Would it be possible running our `jUnit` tests via npm? It'd be great if you could configure the tests that we already have, and then add new tests from these if you want.

 
Thanks again for your time. I await your reply.

**Comment by jtorreggiani** [comment]
@jariazavalverde, are you referring to the Java based `jUnit` (https://junit.org/junit5) or the JavaScript based `jUnit` (https://github.com/ysmood/junit)? If you are referring to the Java library you should be able to run them from the command-line. I believe you can run arbitrary bash commands as an `npm` script. Could look something like this:

```JSON
"scripts": {
  "example:fruit": "node examples/nodejs/fruit",
  "test:jest": "node_modules/.bin/jest spec/jest",
  "test:junit" : "java -jar junit-platform-console-standalone-1.3.2.jar spec/junit"
}

```
If they are written in the javascript library it would be even easier to setup. Either way if you share the tests you already have I would be happy to try to configure them in this repository. We would just want to note in the documentation that future contributors need to have Java installed in order to run the all the tests.

**Comment by jariazavalverde** [comment]
Sorry, I meant to say `qUnit` (https://qunitjs.com/), not `jUnit`. :sweat_smile:  

@josegarciaclm95 will share his tests in the repository tomorrow.

**Comment by josegarciaclm95** [comment]
I've just pushed the tests. They are made to work in the client (in order to run it you must open the `test/index.html` file, which loads the core and the test scripts), but the adaptation needed to make them work for Node should be minimal @jtorreggiani

**Comment by jtorreggiani** [comment]
Thanks, @josegarciaclm95. I will take a look and see what I can do!

**Comment by josegarciaclm95** [comment]
Okay then @jtorreggiani, I'm going to close this pull request so you can fork the repo again and add the tests, yours and ours. Please open a new pull request when you're done!

**Pull request closed without merging**
