### PR TITLE
Add de facto standard epsilon/0 evaluable functor

### PR DESCRIPTION
**Pull request by pmoura**

### CODE REVIEW

**Comment by jburse** [comment]
I tried the new epsilon/0 evaluable functions. Its either too large or
I don't understand the JavaScript floats. I get the following:

grafik

**Comment by jburse** [comment]
But expectation is then, from GNU Prolog, (also on SWI7 and 
upcoming my system):

grafik

**Comment by jburse** [comment]
I hypothesized that it could be a problem of half even rounding.
But half even rounding seems to be ok:

grafik

**Comment by jburse** [comment]
This is the same half even rounding as in GNU Prolog,
on a Windows platform, possibly using the native FPU:

grafik

**Comment by jariazavalverde** [comment]
I think the problem is the type. `1.0 =:= 1` is false in Tau Prolog. I'll check it.

**Comment by jburse** [comment]
Yes, =:= is special. Its not the same as == or =.

**Comment by jariazavalverde** [comment]
Fixed!

arithmetic_comparison

**Pull request merged**
