### PR TITLE
WIP: Add de facto standard forall/2 predicate

### PR DESCRIPTION
**Pull request by pmoura**
Can you please verify the implementation is correct? Is also possible that it can be simplified.

A simple test would be:

    ?- forall(between(1,3,N), write(N)).

### CODE REVIEW

**Comment by jariazavalverde** [comment]
It's ok. Thanks for your commits!

**Comment by jburse** [comment]
You see this also here:
http://www.swi-prolog.org/pldoc/doc/_SWI_/boot/apply.pl?show=src#forall/2

Its simply:

forall(Cond, Action) :-
+ (Cond, + Action).

**Comment by pmoura** [comment]
Prolog case is clear. JavaScript implementation for it not so clear as I'm not familiar with its details. That's why the pull request was tagged WIP and why I wrote "Is also possible that it can be simplified." in its description.

**Comment by jburse** [comment]
From ISO `\+` can be bootstrapped as follows, Prolog text view:

```
\+(X) :- X, !, fail.
\+(_).
```

Which will be stored as follows:

```
\+(X) :- call(X), !, fail.
\+(_).

```
Should also happen one way or the other. Otherwise I guess this 
test case here wont work correctly:

```
?- X = (true, !, fail), \+ X.
true
```

**Comment by jburse** [comment]
If I understand it correctly builtins are somewhere in the Java 
script code, as a sequence of clause constructors (I find a 
couple of files called beta.js I see):

+			"forall/2": function( thread, point, atom ) {
https://github.com/jariazavalverde/tau-prolog/commit/a48b8198fb36ff5d122ed2f74169c91f2d9a3105

Wouldn't it make sense to have builtins bootstrapped in Prolog code itself,
if they are builtins that are not really necessary for the core? On starting up 
the interpreter they would be loaded like a preloaded

module, but on GitHub they would be visible as Prolog text for everybody.
Some file "preloaded.pl", loaded on startup of the Prolog interpreter. Loaded
as soon as the parser and directive processor is initialized:

     forall(A, B) :-  
           \+ (A , \+ B).

Shouldn't slow down the start up of the interpreter. The slow thing
is anyway the network latency and the network transport, but a few
new class versus a little parsing of text doesn't make a difference,

but it could increase maintainability etc..

**Comment by jariazavalverde** [comment]
There are two ways of defining predicates in Tau Prolog:

- As a function: `function( thread, point, atom ) { ... } ` for operations that can't be codified in pure prolog. For example, the [**retract/1**](http://tau-prolog.org/documentation/prolog/builtin/retract/1) predicate needs information about the session.
- As a list of clauses "compiled" into JavaScript for pure prolog operations. For example, the [**append/3**](http://tau-prolog.org/documentation/prolog/lists/append/3) predicate.

Note that, from the point of view of documentation, the implementation of the second kind of predicates can be displayed as Prolog text. In fact, in our website, the code of each predicate is shown directly from the library.

retract1
--
append3

**Comment by jburse** [comment]
But somehow a module is missing. I understand that append/3 is displayed
because it is part of a Prolog text module lists.
But then retract/1 is a built-in that cannot be defined as a Prolog text,

so its displayed by its JavaScript implementation.
But for exampe forall/2 can be defined as Prolog text, nevertheless
itwas defined as JavaScript. Which is a pitty. The problem could be

solved that there were some module "core" or "preloaded", or any
other name, which is Prolog text, and defines some predicates 
from the pseudo module user and is preloaded.

**Comment by jburse** [comment]
I don't find forall/2 yet here:
http://tau-prolog.org/documentation#builtin

But I guess everything from Control Constructs to Input and Output
will be JavaScript. Which is a pitty, since forall/2 could be in some
preloaded user module, as Prolog text.

P.S.: There seems to be a small glitch:

grafik

**Comment by jburse** [comment]
There are more candidates, which can be bootstrapped 
as Prolog text, for example:

```
repeat.
repeat :- repeat.
```

There is also a small glitch:

grafik

**Pull request merged**
